### ISSUE TITLE
consolidate pipe_tee and tjunction examples

### ISSUE THREAD

**Issue by waltersma** [ansys/pyprimemesh#110]
Currently two sets of geometry files with differing setup for different examples.  

Geometry needs consolidating into a single complete set of files (scdoc, fmd, pmdat) with appropriate example scripts.  Capping API now available and workflow could be modified to account for this rather than using wrapper.

**Comment by ninad-kamat** [comment]
@waltersma Is this still an issue?

**Comment by waltersma** [comment]
Fixed.
