### ISSUE TITLE
Project home page links in doc

### ISSUE THREAD

**Issue by waltersma** [ansys/pyprimemesh#169]
@akaszynski , @ninad-kamat  just wondering if the below makes more sense as general guidance for doc home page navigation? Any thoughts?  

![image](https://user-images.githubusercontent.com/104021577/201395977-cf007243-b654-4306-a5ed-12a095c0c80d.png)

**Comment by ninad-kamat** [comment]
@waltersma At present clicking the PyAnsys logo takes you back to the home page. Can you comment on what exactly you are suggesting?

**Comment by waltersma** [comment]
@ninad-kamat it seems odd to me that the pyansys logo takes you to pyprimemesh homepage.  Would it not make more sense for it to send to pyansys homepage and have an extra link in the top banner to pyprimemesh homepage?

**Comment by ninad-kamat** [comment]
@waltersma What should we do with this issue? Have we made any progress with this? It may be more suited to create an issue on [ansys-sphinx-theme](https://github.com/ansys/ansys-sphinx-theme) project instead.

**Comment by waltersma** [comment]
@ninad-kamat done as suggested.
