### ISSUE TITLE
import jt issue with  PartCreationType.PART

### ISSUE THREAD

**Issue by Rohits28** [ansys/pyprimemesh#271]
Hi,

I am working on external aero case. 
observing jt import issue when I use PartCreationType.PART with below error

![image](https://user-images.githubusercontent.com/101093974/207051682-1534d0f8-3420-469c-bbc6-901bc8b40a8e.png)

@waltersma @ninad-kamat @rajesh1359 @ansutremel

**Comment by ninad-kamat** [comment]
@ashishagr25 @waltersma This seems to be fixed and the corresponding issue is closed in ADO. Closing issue.
