### ISSUE TITLE
JT import not working for CadReaderRoute.Native and  CadReaderRoute.Workbench

### ISSUE THREAD

**Issue by Rohits28** [ansys/pyprimemesh#285]
Hi,

I am working on JT import. I saw JT import fails for Native and Workbench route even if I configured Workbench route. 
![image](https://user-images.githubusercontent.com/101093974/208045762-0dacc916-005e-46e2-982d-5e0e751de23f.png)

Rohit

@ansutremel @waltersma @rajesh1359

**Comment by ninad-kamat** [comment]
@ashishagr25 @waltersma This seems to be fixed and the corresponding issue is closed in ADO. Closing issue.
