### ISSUE TITLE
PyVista not listed as a prereq

### ISSUE THREAD

**Issue by hvardhan** [ansys/pyprimemesh#332]
The Getting Started document does not give a list of prerequisites. One discovers PyVista is needed when trying the first example. To clarify, I used command prompt for pyprimemesh installation. The VSCode env gave an issue.

**Comment by waltersma** [comment]
@hvardhan please use "pip install ansys-meshing-prime[all]" to install with graphics dependencies, I think this will fix the issue you have.  I have added a PR to update the docs.

**Comment by ninad-kamat** [comment]
@hvardhan Do you think the changes made by Martin have sufficiently addressed your concern? If so, please let me know and we can close the issue.

**Comment by waltersma** [comment]
@ninad-kamat, @hvardhan closing this issue.  Please re-open if deemed necessary.
