### ISSUE TITLE
Increase default timeout value for launch prime 

### ISSUE THREAD

**Issue by agvarghe** [ansys/pyprimemesh#351]
### 📝 Description of the feature

Its observed that for a new setup of Pyprimemesh , initially while trying to run the scripts an issue is observed , in the form of GRPC Communication error , The resolution provided was to define a timeout to 20(s) in launch prime. 

### 💡 Steps for implementing the feature

The resolution provided was to define a timeout to 20(s) in launch prime.

**Comment by agvarghe** [comment]
![image](https://user-images.githubusercontent.com/113696961/214497652-b8a4caed-c6d7-49c6-9abf-6b75b4be8995.png)

**Comment by ninad-kamat** [comment]
@agvarghe I agree that we should have a better default value. Do we have any data on what is the average time for a license checkout for our clients? I hesitate to just double the existing default as it would be better to have this backed by some concrete data.

**Comment by agvarghe** [comment]
@ninad-kamat 
Sure , i can check this and provide an update
