### ISSUE TITLE
File name does not follow Python convention

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/pyprimemesh#356]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

In [core](https://github.com/pyansys/pyprimemesh/tree/main/src/ansys/meshing/prime/core) folder, the files do not follow the Python naming convention.
For instance, `sizecontrol.py` could be renamed `size_control.py`.

This is probably due to the way the auto-generated files are named when being created.

### 📝 Steps to reproduce

N/A

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
N/A
```

**Comment by ninad-kamat** [comment]
@MaxJPRey I cannot find any mention of such a guideline for file names in PEP8. All I have found is that file names should be lower case. As you pointed out, most of these files follow the same name as the auto generated files. I do not see why the file being named `sizecontrol.py` or `wrappercontrol.py` should be an issue here.

**Comment by AlejandroFernandezLuces** [comment]
Here you can find the guideline regarding the underscores: https://peps.python.org/pep-0008/#package-and-module-names
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability.

Despite it is optional, I do think that it would improve readability. Also, we are using this rule in other `pyansys` repos, so I would prefer to stick to this rule. Some examples:

https://github.com/pyansys/pygeometry/blob/main/src/ansys/geometry/core/primitives/curve_evaluation.py
https://github.com/pyansys/pymapdl/blob/main/src/ansys/mapdl/core/mapdl_console.py
https://github.com/pyansys/pyfluent/blob/main/src/ansys/fluent/core/session_base_meshing.py

**Comment by ninad-kamat** [comment]
Closing this issue for now.
