### ISSUE TITLE
Modify surface meshing user guide is incorrect

### ISSUE THREAD

**Issue by Rohits28** [ansys/pyprimemesh#391]
### Description of the modifications

![image](https://user-images.githubusercontent.com/101093974/220858033-52016ac5-beb8-490f-a6b2-866415849ca9.png)

I am following the user guide for computing sizefield. It seems to be incorrect in res are
User guide showing _**size_field_compute_volumetric**_ instead of _**size_field.compute_volumetric**._ 

### Useful links and references

Link for user guide : https://prime.docs.pyansys.com/release/0.3/user_guide/surfer.html

**Comment by hlee0122** [comment]
Hi @Rohits28 I think we've corrected it in dev.
