### ISSUE TITLE
importing a scdoc

### ISSUE THREAD

**Issue by mcMunich** [ansys/pyprimemesh#466]
Trying to import a .scdoc (or .prt) but receive the response: 
PrimeRuntimeError: JSON Parsing Error - Escape sequence used in the string was not recogonized

import os
import tempfile

from ansys.meshing import prime
from ansys.meshing.prime.graphics import Graphics

modelFile = 'D:\TRRs\2023\05 SGRE Meshing'
model = 'bob.scdoc'
myModel = os.path.join(modelFile,model)

prime_client = prime.launch_prime()
model = prime_client.model

file_io = prime.FileIO(model)

file_io.import_cad(
    file_name=myModel,
    params=prime.ImportCadParams(
        model=model,
        length_unit=prime.LengthUnit.MM,
        part_creation_type=prime.PartCreationType.MODEL,
    ),
)

params = prime.ImportCadParams(
    model=model, cad_reader_route=prime.CadReaderRoute.SPACECLAIM
)
prime.FileIO(model).import_cad(file_name=myModel, params=params)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23r1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
PrimeRuntimeError: JSON Parsing Error - Escape sequence used in the string was not recogonized
```

**Comment by ninad-kamat** [comment]
@mcMunich The issue seems to be that you are using regular string to describe the file path which contains `\` character. I would suggest trying either of the following options.
```python
modelFile = 'D:\\TRRs\\2023\\05 SGRE Meshing'
model = 'bob.scdoc'
myModel = os.path.join(modelFile,model)
```
OR with raw strings in python as
```python
modelFile = r'D:\TRRs\2023\05 SGRE Meshing'
model = 'bob.scdoc'
myModel = os.path.join(modelFile,model)
```

**Comment by mcMunich** [comment]
@ninad-kamat Thanks. I thought I checked that but that was the issue.

**Comment by ninad-kamat** [comment]
I guess we do need to have better error messaging for this. I will create a PR to fix this so that we throw a better error message during import.
