### ISSUE TITLE
Unable to mesh using hex

### ISSUE THREAD

**Issue by mcMunich** [ansys/pyprimemesh#480]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I am trying to mesh a structural model with a quadratic mesh. 

```
maxSize = 100
minSize = 50
eshape = prime.VolumeFillType(n)
mesh_util.surface_mesh(min_size = minSize, max_size = maxSize ,generate_quads = True )
mesh_util.volume_mesh(volume_fill_type = eshape)

```
only n = 0 seems to work but that creates tets with the surface quad and 1,2,3 generate an error when saving to file.

If n = 1
```
structural_mesh = os.path.join(here, file + '_QUAD.cdb')
mesh_util.write(structural_mesh)

```
returns 

_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50063 {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-05-23T10:21:43.964883399+00:00"}"
>

### 📝 Steps to reproduce

See code above

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23r1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
xxx
```

**Comment by ninad-kamat** [comment]
@mcMunich Could you please share the input file that you are using?

**Comment by mcMunich** [comment]
I can send it but let me get confirmation from the customer and account manager. 
One thing is weird I can get a plot of the mesh and even the quality, but it now fails when I try to write the cdb.

```
_MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50062 {created_time:"2023-05-24T13:19:55.329116117+00:00", grpc_status:2, grpc_message:"Stream removed"}"
>
```

**Comment by waltersma** [comment]
@mcMunich cdb format does not support poly mesh type.  #205 will fix this.  The #volumefilltype you are using with the exception of #ansys.meshing.prime.VolumeFillType.TET all contain poly.

When you say quadratic I understand you to mean hex from the context of the discussion but if you wish to get linear quadratic tet elements you can use #ansys.meshing.prime.TetParams.quadratic.

We have only recently begun to expose hex meshing capabilities.  At 0.4.0 VolumeSweeper (Stacker) and ThinVolumeControl will be capable of hex meshing in certain scenarios.

**Comment by mcMunich** [comment]
@waltersma I was trying out the pcb example and the Volumesweeper seems to give an error:

    sweeper = prime.VolumeSweeper(model)

AttributeError: module 'ansys.meshing.prime' has no attribute 'VolumeSweeper'

I think I have the most updated version; 
"C:\spyderEnv\Scripts\pip" install ansys-meshing-prime[all]

**Comment by waltersma** [comment]
Closing this issue as original question is answered.  For the second issue mentioned please open a new issue if this is reproducible after confirming this is not a client server compatibility issue (see https://prime.docs.pyansys.com/version/stable/getting_started/index.html for client server compatibility).

Thanks
