### ISSUE TITLE
PyVista._vtk doesn't have a vtkPNGReader attribute

### ISSUE THREAD

**Issue by AdamTheEngineer-dev** [ansys/pyprimemesh#486]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I'm trying to run the basic elbow examples but I keep getting this error:

  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\PyPrimeMesh\.venv\lib\site-packages\ansys\meshing\prime\graphics\graphics.py", line 609, in __update_bt_icons
    r = _vtk.vtkPNGReader()
AttributeError: module 'pyvista._vtk' has no attribute 'vtkPNGReader'. Did you mean: 'vtkPLYReader'?

I have the latest pyvista installed.

### 📝 Steps to reproduce

Try to run : 
 python elbow.py 

in a venv with the latest ansys-meshing-prime[all] 
installed with pip.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-meshing-prime==0.1.1
ansys-meshing-prime==0.3.1
appdirs==1.4.4
certifi==2023.5.7
charset-normalizer==3.1.0
contourpy==1.0.7
cycler==0.11.0
fonttools==4.39.4
grpcio==1.54.2
idna==3.4
kiwisolver==1.4.4
matplotlib==3.7.1
numpy==1.24.3
packaging==23.1
Pillow==9.5.0
platformdirs==3.5.1
pooch==1.7.0
protobuf==3.20.3
pyparsing==3.0.9
python-dateutil==2.8.2
pyvista==0.39.1
requests==2.31.0
scooby==0.7.2
six==1.16.0
urllib3==2.0.2
vtk==9.2.6
```

**Comment by AlejandroFernandezLuces** [comment]
Closed by #487
