### ISSUE TITLE
Unable use the quality measure ELEMENTQUALITY

### ISSUE THREAD

**Issue by mcMunich** [ansys/pyprimemesh#499]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Every time I change the **prime.CellQualityMeasure.SKEWNESS** to **prime.CellQualityMeasure.ELEMENTQUALITY** I get a 
`PrimeRuntimeError: Volume search failed.`

### 📝 Steps to reproduce

After it failed in my solid model, I tried to change the quality parameter in the mixing elbow model.  Same error there.

`PrimeRuntimeError: Volume search failed.`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23r1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by mcMunich** [comment]
Here is the script:

```
cell_quality_measures = prime.CellQualityMeasure.ELEMENTQUALITY
quality = prime.VolumeSearch(model)
quality_params = prime.VolumeQualitySummaryParams(
    model=model,
    scope=prime.ScopeDefinition(model=model),
    cell_quality_measures=[cell_quality_measures],
    quality_limit=[1],
)
qual_summary_res = quality.get_volume_quality_summary(quality_params)
```
The actual failure occurs in the last line.

**Comment by hlee0122** [comment]
Hi @mcMunich this is a known issue and we've fixed it in the dev code. Can you try the dev8 pre-released version and see if you still have the issue searching for element quality?

**Comment by waltersma** [comment]
@mcMunich closing this issue for now but please reopen if you see anything further. (Cc @hlee0122)

**Comment by mcMunich** [comment]
now the line will print the results if the CellQualityMeasure is set to quality but the return still lists skew (which might just be a typo in the code).

`    cell_quality_measures = prime.CellQualityMeasure.ELEMENTQUALITY 
    quality = prime.VolumeSearch(model)
    quality_params = prime.VolumeQualitySummaryParams(
        model=model,
        scope=prime.ScopeDefinition(model=model),
        cell_quality_measures=[cell_quality_measures],
        quality_limit=[0.5],
    )
    qual_summary_res = quality.get_volume_quality_summary(quality_params)
    print(qual_summary_res)`

returns:

error_code :  0
quality_results_part :  [
cell_quality_measure :  50
measure_name :  ElementQuality
part_id :  2
quality_limit :  0.5
n_found :  3481
max_quality :  0.999999
min_quality :  0.205225]
message :  ElementQuality
    Part ID: m1
    Quality Limit: 0.5
        Number of failures: 3481
        Max Skew: 0.999999
        Min Skew: 0.205225
Summary Results:
    Number of failures: 3481
    Max Skew: 0.999999
    Min Skew: 0.205225

I think the values are correct, but the text misleading (skew s/b elementquality). If I set the quality measure back to skewness I get different values (so it appears to be working) with Max/Min Skew.

**Comment by hlee0122** [comment]
APS 928913
