### ISSUE TITLE
Can't start pyprime instance due to Ansys License Manager Error

### ISSUE THREAD

**Issue by mcMunich** [ansys/pyprimemesh#502]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When I start a pyprime session, sometimes I get this error and then I have to restart my computer.

`prime_session= prime.launch_prime()`

Restarting the pykernel, restarting the IDE does not seem to work.

![image](https://github.com/ansys/pyprimemesh/assets/84008975/635f6484-c756-432c-a498-547cb531946f)

### 📝 Steps to reproduce

Launch prime_session= prime.launch_prime()

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23r1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
NA
```

**Comment by mcMunich** [comment]
What is happening is pyprime is 1. not returning licenses and 2. continuing to check them out. 
my licsense log:

11:27:58 (ansyslmd) (@ansyslmd-SLOG@) Running on Hypervisor: Not determined - treat as Physical
11:27:58 (ansyslmd) (@ansyslmd-SLOG@) ===============================================
11:28:02 (ansyslmd) TCP_NODELAY NOT enabled
11:28:03 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [17944] 
11:28:06 (ansyslmd) OUT: "disco_level1" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [21364] 
11:28:17 (ansyslmd) IN: "disco_level1" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [21364] 
11:28:53 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [7300] 
11:28:59 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [13508] 
11:29:05 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [22292] 
11:29:15 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [12024] 
11:29:19 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [13492] 
11:29:19 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [7996] 
11:29:29 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [14396] 
11:29:32 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [8908] 
11:29:33 (ansyslmd) OUT: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [7928] 
11:29:33 (ansyslmd) DENIED: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (Licensed number of users already reached. (-4,342))
11:29:33 (ansyslmd) UNSUPPORTED: "cfd-preppost" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (No such feature exists. (-5,346))
11:29:33 (ansyslmd) UNSUPPORTED: "advanced-meshing" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (No such feature exists. (-5,346))
11:29:35 (ansyslmd) DENIED: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [6080] (Licensed number of users already reached. (-4,342))
11:29:35 (ansyslmd) DENIED: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [6080] (Licensed number of users already reached. (-4,342))
11:31:34 (ansyslmd) DENIED: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (Licensed number of users already reached. (-4,342))
11:31:34 (ansyslmd) UNSUPPORTED: "cfd-preppost" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (No such feature exists. (-5,346))
11:31:34 (ansyslmd) UNSUPPORTED: "advanced-meshing" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (No such feature exists. (-5,346))
11:31:35 (ansyslmd) DENIED: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [6080] (Licensed number of users already reached. (-4,342))
11:31:35 (ansyslmd) UNSUPPORTED: "cfd-preppost" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [6080] (No such feature exists. (-5,346))
11:31:35 (ansyslmd) UNSUPPORTED: "advanced-meshing" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [6080] (No such feature exists. (-5,346))
11:33:33 (ansyslmd) DENIED: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (Licensed number of users already reached. (-4,342))
11:33:33 (ansyslmd) UNSUPPORTED: "cfd-preppost" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (No such feature exists. (-5,346))
11:33:33 (ansyslmd) UNSUPPORTED: "advanced-meshing" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [9720] (No such feature exists. (-5,346))
11:33:34 (ansyslmd) DENIED: "preppost" mcapella@AAPm6rO39sAC9IK.win.ansys.com  [6080] (Licensed number of users already reached. (-4,342))
11:33:34 (ansyslmd) UNSUPPORTED: "cfd-preppost" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [6080] (No such feature exists. (-5,346))
11:33:34 (ansyslmd) UNSUPPORTED: "advanced-meshing" (PORT_AT_HOST_PLUS   ) mcapella@AAPm6rO39sAC9IK.win.ansys.com  [6080] (No such feature exists. (-5,346))

**Comment by mcMunich** [comment]
Solution: use python

At the end of your script or if you get the out of license message, you can use os. taskill to kill ALL of the .exe that are holding the licenses. This will kill them all. caveat sciptor.
```

import os
os.system("taskkill /f /im  AnsysPrimeServer.exe")
```

**Comment by ninad-kamat** [comment]
Closing this issue as we are working on a solution to provide licensing errors as part of addressing #2 .
