### ISSUE TITLE
Modify ...Stacker mesh user guide has some incorrect phrases

### ISSUE THREAD

**Issue by agvarghe** [ansys/pyprimemesh#533]
### Description of the modifications

In the description for Volume Sweeping, i am seeing some sentance like `vale on` , An image for the same can be found below 

![image](https://github.com/ansys/pyprimemesh/assets/113696961/b64c41c3-0de4-4d9d-b8e7-edf35ae15c22)

### Useful links and references

https://prime.docs.pyansys.com/version/dev/user_guide/stacker.html

**Comment by hlee0122** [comment]
@agvarghe @waltersma Doc has been corrected and merged. Will close this issue.
