### ISSUE TITLE
pyprimemesh sometimes writes last node of eblock as -1 during cdb export

### ISSUE THREAD

**Issue by tletutour-an** [ansys/pyprimemesh#628]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I have only seen this happening when trying to write meshes with a lot of elements to cdb. 

![image](https://github.com/ansys/pyprimemesh/assets/64088931/cd88e975-435e-4b39-912c-4a114fe988d3)

When this happens, the reading of eblock command in APDL will fail and give this error : 

 *** FATAL ***                           CP =      59.984   TIME= 14:56:29
 Error in reading formats in the EBLOCK command.  This may be due to an  
 incorrect transfer from/to linux and windows.  Use ftp (ASCII mode) or  
 dos2unix to properly account for system differences.                    

 ************************************************************************
 The above error is non-recoverable by ANSYS                             
  ANSYS run terminated by the indicated error                            
  Current data base saved if possible.                                   
 ************************************************************************

### 📝 Steps to reproduce

Run this code and try to read the mesh using APDL or pymapdl
`import ansys.meshing.prime.graphics as graphics
from ansys.meshing import prime
from ansys.meshing.prime import lucid
import time
from ansys.mapdl.core import launch_mapdl
import numpy as np
import os

if __name__ == "__main__":
        min_sizes = list(np.linspace(0.1, 1, 10))
        min_sizes.reverse()
        for min_size in min_sizes:
            min_size_m = min_size * 1e-3
            max_size_m = min_size * 1.5 * 1e-3

            if not os.path.exists("D:\\sandbox\\prime_meshes\\min{}_prime.cdb".format(min_size)):

                with prime.launch_prime(version = 232, timeout=45) as prime_client:    
                    model = prime_client.model
                    file_io = prime.FileIO(model)
                    mesh_util = lucid.Mesh(model)
                    file_name = "D:\\geometries\\simple_geometry_test_ns.scdoc"
                    
                    print("starting CAD read")
                    t_start = time.time()
                    file_io.import_cad(file_name=file_name, params = prime.ImportCadParams(model=model, cad_reader_route=prime.CadReaderRoute.WORKBENCH, length_unit=prime.LengthUnit.M))

                    print("CAD read done in", time.time() - t_start)
                    t_start = time.time()
                    print(model)
                    sizing_params = prime.GlobalSizingParams(model=model, min=min_size_m, max=max_size_m)
                    model.set_global_sizing_params(params=sizing_params)
                    mesh_util.surface_mesh()
                    mesh_util.create_zones_from_labels()
                    print(model)
                    print("Done with surface meshing in", time.time() - t_start)
                    print("Starting volume meshing")
                    auto_mesh_params = prime.AutoMeshParams(model=model,max_size=max_size_m)
                    auto_mesh_params.volume_fill_type = prime.VolumeFillType.TET
                    volume_mesh = prime.AutoMesh(model=model)    
                    volume_mesh.mesh(part_id=model.parts[0].id,automesh_params=auto_mesh_params)
                    print("volume meshing done in", time.time() - t_start)
                    results = mesh_util.write(file_name = "D:\\sandbox\\prime_meshes\\min{}_prime.cdb".format(min_size))
                    `

Mesh with larger size are correct and start to not work at 0.4 for me.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

23R2

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
alabaster==0.7.13
ansys-api-fluent==0.3.18
ansys-api-mapdl==0.5.1
ansys-api-meshing-prime==0.1.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-corba==0.1.1
ansys-dpf-core==0.9.0
ansys-dpf-gate==0.4.1
ansys-dpf-gatebin==0.4.1
ansys-dpf-post==0.5.0
ansys-fluent-core==0.17.1
ansys-grpc-dpf==0.8.1
ansys-mapdl-core==0.67.0
ansys-mapdl-reader==0.52.13
ansys-math-core==0.1.3
ansys-meshing-prime==0.4.1
ansys-platform-instancemanagement==1.1.1
-e git+https://github.com/ansys/pyscs-lib.git@0f74cfc23407e7fa5073b1f774ba47911c7b3540#egg=ansys_scs_lib
ansys-sphinx-theme==0.4.2
ansys-tools-path==0.3.1
appdirs==1.4.4
atomicwrites==1.4.1
attrs==23.1.0
Babel==2.12.1
beautifulsoup4==4.12.2
build==0.8.0
cachetools==5.3.1
certifi==2023.5.7
chardet==5.2.0
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
contourpy==1.0.7
coverage==7.3.1
cycler==0.11.0
dcm2niix==1.0.20220715
distlib==0.3.7
docker==6.1.3
docutils==0.18.1
et-xmlfile==1.1.0
filelock==3.12.3
fonttools==4.39.4
fsspec==2023.9.2
geomdl==5.3.1
google-api-core==2.11.1
google-api-python-client==2.100.0
google-auth==2.23.0
google-auth-httplib2==0.1.1
googleapis-common-protos==1.59.0
grpcio==1.54.2
grpcio-health-checking==1.48.2
h5py==3.10.0
httplib2==0.22.0
idna==3.4
imageio==2.31.3
imagesize==1.4.1
importlib-metadata==4.13.0
importlib-resources==5.12.0
iniconfig==2.0.0
install==1.3.5
itk==5.3.0
itk-core==5.3.0
itk-elastix==0.17.1
itk-filtering==5.3.0
itk-io==5.3.0
itk-numerics==5.3.0
itk-registration==5.3.0
itk-segmentation==5.3.0
jaraco.classes==3.3.0
Jinja2==3.1.2
joblib==1.3.2
keyring==24.2.0
kiwisolver==1.4.4
lazy_loader==0.3
lxml==4.9.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.1
mdurl==0.1.2
miutil==0.12.0
more-itertools==10.1.0
mpmath==1.3.0
networkx==3.1
NEURON==8.2.2
nh3==0.2.14
nibabel==5.1.0
nilearn==0.10.1
numpy==1.24.3
numpydoc==1.4.0
openpyxl==3.1.2
packaging==23.1
pandas==2.0.3
pep517==0.13.0
Pillow==9.5.0
pkginfo==1.9.6
platformdirs==3.10.0
pluggy==1.3.0
pooch==1.7.0
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil==5.9.5
py==1.11.0
pyansys-tools-versioning==0.3.3
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydata-sphinx-theme==0.9.0
Pygments==2.16.1
pyiges==0.3.1
pyparsing==3.0.9
pyproject-api==1.6.1
pytest==7.1.2
pytest-cov==3.0.0
python-dateutil==2.8.2
pytz==2023.3.post1
pyvista==0.38.6
PyWavelets==1.4.1
pywin32==306
pywin32-ctypes==0.2.2
PyYAML==6.0.1
readme-renderer==42.0
requests==2.31.0
requests-toolbelt==1.0.0
rfc3986==2.0.0
rich==13.5.2
rsa==4.9
scikit-image==0.21.0
scikit-learn==1.3.0
scipy==1.10.1
scooby==0.7.2
SimpleITK==2.3.0
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==5.0.2
sphinx-copybutton==0.5.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
sympy==1.12
threadpoolctl==3.2.0
tifffile==2023.7.10
tomli==2.0.1
torchvision==0.16.0
tox==4.11.3
tqdm==4.65.0
twine==4.0.1
typing_extensions==4.7.1
tzdata==2023.3
uritemplate==4.1.1
urllib3==1.26.16
virtualenv==20.24.5
vtk==9.2.6
websocket-client==1.6.4
zipp==3.15.0
```

**Comment by waltersma** [comment]
Logged an issue with the server.
APS 924991
