### ISSUE TITLE
import of parasolid .x_t issue

### ISSUE THREAD

**Issue by mcMunich** [ansys/pyprimemesh#633]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I have a parasolid model generated first in pymadl and converted to .x_t with Ansys discovery. The geometry looks fine in Disco but  when imported into pyprime a small piece is missing from the outer ring of the model. 

disco .x_t model image
![image](https://github.com/ansys/pyprimemesh/assets/84008975/d25cf97f-103e-42a6-963b-28ff331b0c83)
pyprime display:
![image](https://github.com/ansys/pyprimemesh/assets/84008975/d9166d0d-0a1f-4271-97f0-b93a4e65d071)
zoom to the issue: 
![image](https://github.com/ansys/pyprimemesh/assets/84008975/c6da1758-ff01-4b5b-99cb-e4dc11cac32a)
prime actually meshes the geometry, so something is working. But the geometry when imported is wrong. 

### 📝 Steps to reproduce

[NewDesign.zip](https://github.com/ansys/pyprimemesh/files/13185563/NewDesign.zip)

Run the attached script on the attached model and check the plots. You can also open the .x_t in another tool to check if the geo is actually okay. 

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

232

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
x
```

**Comment by waltersma** [comment]
@mcMunich this appears to be an issue with the Native parasolid reader route that is the program controlled route.  If you have access to an installation with SpaceClaim or Workbench readers you will be able to use these to avoid this issue. 

for example: mesher.read(inputFile,cad_reader_route=prime.CadReaderRoute.SPACECLAIM)

 I have logged an issue with the server: APS 928513

**Comment by waltersma** [comment]
@mcMunich it is an issue with the ACIS faceter used in this instance.

You can get the desired behaviour using the Parasolid faceter instead, as shown below:

refaceter_params = prime.CadRefacetingParams(model, cad_faceter=prime.CadFaceter.PARASOLID)
cad_params = prime.ImportCadParams(model, cad_reader_route=prime.CadReaderRoute.NATIVE, cad_refaceting_params=refaceter_params)
prime.FileIO(model).import_cad(inputFile, params=cad_params)

Please reopen if this does not fix your issue.
