### ISSUE TITLE
Bug located in api reference not published for topodata

### ISSUE THREAD

**Issue by waltersma** [ansys/pyprimemesh#641]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

src/ansys/meshing/prime/autogen/topodata.py not generating api references.

### 📝 Steps to reproduce

No api docs generated for this autogen file

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

NA

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
NA
```

**Comment by srpyprime** [comment]
Added tfs bug to track the same
https://tfs.ansys.com:8443/tfs/ANSYS_Development/Portfolio/_workitems/edit/953912/
