### ISSUE TITLE
Modify ...User guide data missing in the dev documentation

### ISSUE THREAD

**Issue by agvarghe** [ansys/pyprimemesh#696]
### Description of the modifications

The dev build of user guide documentation appears to be missing information that is present in 0.4.1 version 

### Useful links and references

https://prime.docs.pyansys.com/version/dev/user_guide/index.html

**Comment by waltersma** [comment]
@agvarghe this is being looked at by @AlejandroFernandezLuces, thanks

**Comment by AlejandroFernandezLuces** [comment]
This is fixed, I just did a patch release to update the faulty dependency. Closing the issue.
