### ISSUE TITLE
Bug: ansys-meshing-prime versions > 0.3.0.dev0 are not available when using the Ansys Private Pypi as main index.

### ISSUE THREAD

**Issue by anscfrisson** [ansys/pyprimemesh#760]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

From:
https://dev.docs.pyansys.com/how-to/releasing.html#artifact-download

> Warning
> 
> Take care to always use the --index-url switch rather than the --extra-index-url switch. As noted in [pip Documentation](https://pip.pypa.io/en/stable/cli/pip_install/), the --index-url switch changes the Python Package Index, which forces pip to use only packages from that package index.
> 
> The Ansys package index uses PyPI upstream. This prevents other users from being able to inject packages from PyPI that would supersede Ansys packages, even if they are of a higher version.
> 
> This is not the case if you use --extra-index-url, which adds to rather than replaces the default package index. For security, do not use --extra-index-url.

If I define environment variables in github actions:
* `PIP_EXTRA_INDEX_URL: "https://${{ secrets.PYANSYS_PRIVATE_PYPI_PAT }}@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"`: `ansys-meshing-prime` can be retrieved
* `PIP_INDEX_URL: "https://${{ secrets.PYANSYS_PRIVATE_PYPI_PAT }}@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"`: fails with:
    ```
    ERROR: Could not find a version that satisfies the requirement ansys-meshing-prime<0.7.0,>=v0.6.0.dev7 (from ***) (from versions: 0.2.0.dev0, 0.2.0.dev17, 0.2.0.dev18, 0.2.0, 0.3.0.dev0)
    ```
(`***` internal project)

Are ansys-meshing-prime versions > 0.3.0.dev0 not relayed by the Ansys Private Pypi?

### 📝 Steps to reproduce

Request the value of the `PYANSYS_PYPI_PRIVATE_READ_PAT` token by sending an email to the [pyansys.core@ansys.com](mailto:pyansys.core%40ansys.com) email.

## Works

```bash
export PIP_INDEX_URL=
export PIP_EXTRA_INDEX_URL="https://$PYANSYS_PYPI_PRIVATE_READ_PAT@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"
pip install ansys-meshing-prime==v0.6.0.dev7
```

```error
Looking in indexes: https://pypi.org/simple, https://****@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple
Collecting ansys-meshing-prime==v0.6.0.dev7
  Downloading ansys_meshing_prime-0.6.0.dev7-py3-none-any.whl (398 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.2/398.2 kB 3.6 MB/s eta 0:00:00
...
```

## Fails

```bash
export PIP_INDEX_URL="https://$PYANSYS_PYPI_PRIVATE_READ_PAT@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple"
export PIP_EXTRA_INDEX_URL=
pip install ansys-meshing-prime=v0.6.0.dev7
```

```pip
Looking in indexes: https://****@pkgs.dev.azure.com/pyansys/_packaging/pyansys/pypi/simple
ERROR: Could not find a version that satisfies the requirement ansys-meshing-prime==v0.6.0.dev7 (from versions: 0.2.0.dev0, 0.2.0.dev17, 0.2.0.dev18, 0.2.0, 0.3.0.dev0)
ERROR: No matching distribution found for ansys-meshing-prime==v0.6.0.dev7
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
(none: tested from new virtual environment)
```

**Comment by rchopade7** [comment]
@anscfrisson 0.6.0.dev client packages are not published to pyansys/pypi, that is why you are not able to install latest pyprimemesh dev client when you set PIP_INDEX_URL to pyansys/pypi.

cc @prajaktmahajan @waltersma

**Comment by RobPasMue** [comment]
I just did some modifications to enable ansys-meshing-prime and ansys-api-meshing-prime upstream versions (i.e. from public PyPI)

**Comment by anscfrisson** [comment]
@RobPasMue Thanks for the updates! I can confirm via CI checks in a private repository that the ansys private pypi works as pip index (using environment variable `PIP_INDEX_URL` instead of `PIP_EXTRA_INDEX_URL`) to relay pyprimemesh packages. Closing issue.
