### ISSUE TITLE
Bug located in ...VolumeSearch fails for multiple cell quality measures 

### ISSUE THREAD

**Issue by agvarghe** [ansys/pyprimemesh#763]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When quering for multiple cell quality parameters, Volume search appears to be crashing.

CC: @waltersma 

### 📝 Steps to reproduce

vol_mesh_statistics = prime.VolumeSearch(model)
    quality_summary = vol_mesh_statistics.get_volume_quality_summary(
        params=prime.VolumeQualitySummaryParams(
            model,
            cell_quality_measures=[
                prime.CellQualityMeasure.SKEWNESS,
                prime.CellQualityMeasure.ASPECTRATIO,
                prime.CellQualityMeasure.ELEMENTQUALITY,
            ],
            scope=prime.ScopeDefinition(model, part_expression=part.name),
            quality_limit=[0.999,250,0.3]
        )
    )
    max_skewness = quality_summary.quality_results_part[0].max_quality
    max_aspect_ratio = quality_summary.quality_results_part[1].max_quality
    min_element_quality = quality_summary.quality_results_part[2].min_quality
    print(max_skewness)
    print(max_aspect_ratio)
    print(min_element_quality)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-meshing-prime==0.6.0.dev7
```

**Comment by waltersma** [comment]
APS 1031380

**Comment by waltersma** [comment]
Fixed for 0.6.1
