### ISSUE TITLE
Modify documentation for CAD import 

### ISSUE THREAD

**Issue by agvarghe** [ansys/pyprimemesh#807]
### Description of the modifications

The documenttaion for CAd import requires correction, 

In the following link 
https://prime.docs.pyansys.com/version/stable/api/_autosummary/ansys.meshing.prime.FileIO.import_cad.html#import-cad
![image](https://github.com/ansys/pyprimemesh/assets/113696961/6ccf099e-afcf-4a07-b3a8-d0f130cc1f58)

its shows "params = ImportCadParams(model=model)"

Insteas it should be 

"params = prime.ImportCadParams(model=model))

### Useful links and references

https://prime.docs.pyansys.com/version/stable/api/_autosummary/ansys.meshing.prime.FileIO.import_cad.html#import-cad

**Comment by waltersma** [comment]
APS 1075044
