### ISSUE TITLE
PyPrimeMesh CAD read error

### ISSUE THREAD

**Issue by agrishin** [ansys/pyprimemesh#871]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I have not gotten very far here. I have installed 3.10.11 and the 0.5.1 version of PyPrimeMesh which is what is listed as matching my 2024R1 installation. I am consistently getting that same error message (see below) except for the native .pmdat format. I will install 2024R2 later today but I would rather not mess with the ANSYS Python manager since I don’t want to corrupt the Python installations that I use in other projects.

Regardless of the example or the CAD file, I am always getting a PrimeRuntimeError: CAD import failed error. I am wondering if there is a CAD importer configuration or setup issue with the ANSYS installation. Any suggestions?

In [1]: from ansys.meshing import prime
   ...:
   ...: # Start and connect to an Ansys Prime Server instance
   ...: prime_client = prime.launch_prime()
   ...: model = prime_client.model
   ...:
   ...: # Instantiate the lucid class
   ...: mesh_util = prime.lucid.Mesh(model=model)
   ...:
   ...: # Read the geometry
   ...: mesh_util.read("mixing_elbow.scdoc")
   ...:
   ...: # Mesh the geometry with a poly prism mesh
   ...: mesh_util.surface_mesh(min_size=5, max_size=20)
   ...:
   ...: mesh_util.volume_mesh(
   ...:     volume_fill_type=prime.VolumeFillType.POLY,
   ...:     prism_surface_expression="* !inlet !outlet",
   ...:     prism_layers=3,
   ...: )
   ...:
   ...: # Prepare and write the model for the Fluent solver
   ...: mesh_util.create_zones_from_labels()
   ...: mesh_util.write("mixing_elbow.cas")
---------------------------------------------------------------------------
PrimeRuntimeError                         Traceback (most recent call last)
Cell In[1], line 11
      8 mesh_util = prime.lucid.Mesh(model=model)
     10 # Read the geometry
---> 11 mesh_util.read("mixing_elbow.scdoc")
     13 # Mesh the geometry with a poly prism mesh
     14 mesh_util.surface_mesh(min_size=5, max_size=20)

File c:\users\e092220\.venv\3.9.6\pyansys-latest\lib\site-packages\ansys\meshing\prime\lucid\mesh_util.py:92, in Mesh.read(self, file_name, append, cad_reader_route)
     88     prime.FileIO(self._model).read_pmdat(
     89         file_name, prime.FileReadParams(self._model, append=append)
     90     )
     91 else:
---> 92     prime.FileIO(self._model).import_cad(
     93         file_name,
     94         prime.ImportCadParams(
     95             self._model, append=append, cad_reader_route=cad_reader_route
     96         ),
     97     )

File c:\users\e092220\.venv\3.9.6\pyansys-latest\lib\site-packages\ansys\meshing\prime\core\fileio.py:504, in FileIO.import_cad(self, file_name, params)
    461 r"""Import a CAD file from disk.
    462
    463 Supported CAD file formats on Windows are:
   (...)
    501
    502 """
    503 with utils.file_read_context(self._model, file_name) as temp_file_name:
--> 504     import_result = super().import_cad(temp_file_name, params)
    505     if import_result.error_code == ErrorCode.NOERROR:
    506         self._model._sync_up_model()

File c:\users\e092220\.venv\3.9.6\pyansys-latest\lib\site-packages\ansys\meshing\prime\autogen\fileio.py:650, in FileIO.import_cad(self, file_name, import_cad_params)
    648 command_name = "PrimeMesh::FileIO/ImportCAD"
    649 self._model._print_logs_before_command("import_cad", args)
--> 650 result = self._comm.serve(self._model, command_name, self._object_id, args=args)
    651 self._model._print_logs_after_command("import_cad", ImportCadResults(model = self._model, json_data = result))
    652 return ImportCadResults(model = self._model, json_data = result)

File c:\users\e092220\.venv\3.9.6\pyansys-latest\lib\site-packages\ansys\meshing\prime\internals\error_handling.py:535, in error_code_handler.<locals>.decorator_error_code.<locals>.wrapper_error_code(*args, **kwargs)
    529     if error_code > 0:
    530         error_location_msg = (
    531             f'\nError Locations: {error_locations}'
    532             if len(error_locations) > 0
    533             else f''
    534         )
--> 535         raise PrimeRuntimeError(
    536             prime_error_messages.get(
    537                 ErrorCode(error_code), f'Unrecogonized error code {error_code}'
    538             )
    539             + error_location_msg,
    540             ErrorCode(error_code),
    541             error_locations,
    542         )
    544 prime_warnings = []
    545 single_warning = result.get('warningCode', None)

PrimeRuntimeError: CAD import failed.

### 📝 Steps to reproduce

PADT: I was able to replicate the error with Python 3.11 for one of the PyPrimeMesh examples, but it worked for Python 3.10.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Running Ansys 2024R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pip freeze output:
about-time==4.2.1
aiohappyeyeballs==2.4.0
aiohttp==3.10.5
aiosignal==1.3.1
alive-progress==3.1.5
annotated-types==0.7.0
ansys-acp-core==0.1b2
ansys-additive-core==0.18.1
ansys-additive-widgets==0.2.1
ansys-api-acp==0.1.0.dev9
ansys-api-additive==1.7.2
ansys-api-dbu==0.3.4
ansys-api-dyna==0.3.6
ansys-api-edb==1.0.6
ansys-api-fluent==0.3.27
ansys-api-geometry==0.4.6
ansys-api-mapdl==0.5.2
ansys-api-mechanical==0.1.2
ansys-api-meshing-prime==0.1.3
ansys-api-modelcenter==0.3.1
ansys-api-platform-instancemanagement==1.1.0
ansys-api-pyensight==0.4.1
ansys-api-sherlock==0.1.27
ansys-api-systemcoupling==0.1.0
ansys-api-tools-filetransfer==0.1.0
ansys-api-workbench==0.2.0
ansys-conceptev-core==0.1.4
ansys-dpf-composites==0.5.0
ansys-dpf-core==0.12.2
ansys-dpf-post==0.8.0
ansys-dyna-core==0.4.15
ansys-dynamicreporting-core==0.6.0
ansys-edb-core==0.1.6
ansys-engineeringworkflow-api==0.1.0
ansys-fluent-core==0.22.0
ansys-geometry-core==0.6.6
ansys-grantami-bomanalytics==2.1.1
ansys-grantami-bomanalytics-openapi==3.0.0
ansys-grantami-jobqueue==1.0.1
ansys-grantami-recordlists==1.2.1
ansys-grantami-serverapi-openapi==3.0.0
ansys-hps-client==0.8.0
ansys-mapdl-core==0.68.4
ansys-mapdl-reader==0.54.0
ansys-math-core==0.1.5
ansys-mechanical-core==0.11.5
ansys-mechanical-env==0.1.7
ansys-meshing-prime==0.6.2
ansys-modelcenter-workflow==0.1.1
ansys-motorcad-core==0.5.5
ansys-openapi-common==2.1.1
ansys-optislang-core==0.8.0
ansys-platform-instancemanagement==1.1.2
ansys-pyensight-core==0.8.8
ansys-pythonnet==3.1.0rc3
ansys-rocky-core==0.2.0
ansys-seascape==0.2.0
ansys-sherlock-core==0.6.0
ansys-simai-core==0.2.2
ansys-sound-core==0.1.3
ansys-systemcoupling-core==0.6
ansys-tools-filetransfer==0.1.0
ansys-tools-local-product-launcher==0.1.0
ansys-tools-path==0.6.0
ansys-tools-visualization-interface==0.4.1
ansys-turbogrid-api==0.4.3
ansys-turbogrid-core==0.4.1
ansys-units==0.3.2
ansys-workbench-core==0.6.0
anyio==4.4.0
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asgiref==3.8.1
asttokens==2.4.1
async-lru==2.0.4
async-timeout==4.0.3
attrs==24.2.0
babel==2.16.0
backoff==2.2.1
backports.entry-points-selectable==1.3.0
backports.tarfile==1.2.0
bcrypt==4.2.0
beartype==0.18.5
beautifulsoup4==4.12.3
bleach==6.1.0
bokeh==3.4.3
build==1.2.1
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.2
contourpy==1.3.0
cryptography==43.0.1
cycler==0.12.1
debugpy==1.8.5
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
dill==0.3.8
Django==5.1.1
docker==7.1.0
docutils==0.21.2
elementpath==4.4.0
exceptiongroup==1.2.2
executing==2.1.0
fabric==3.2.2
fastjsonschema==2.20.0
filelock==3.15.4
flexcache==0.3
flexparser==0.3.1
fonttools==4.53.1
fpdf2==2.7.9
fqdn==1.5.1
frozenlist==1.4.1
geomdl==5.3.1
google-api-core==2.19.2
google-api-python-client==2.143.0
google-auth==2.34.0
google-auth-httplib2==0.2.0
googleapis-common-protos==1.65.0
grapheme==0.6.0
grpcio==1.66.1
grpcio-health-checking==1.48.2
grpcio-status==1.48.2
h11==0.14.0
httpcore==1.0.5
httplib2==0.22.0
httpx==0.26.0
idna==3.8
importlib_metadata==8.4.0
invoke==2.2.0
ipykernel==6.29.5
ipython==8.27.0
ipywidgets==8.1.5
isoduration==20.11.0
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.0.2
jedi==0.19.1
Jinja2==3.1.4
joblib==1.4.2
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter==1.1.1
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.13
keyring==25.3.0
kiwisolver==1.4.6
linkify-it-py==2.0.3
lxml==5.3.0
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.22.0
marshmallow-oneofschema==3.1.1
matplotlib==3.9.2
matplotlib-inline==0.1.7
mdit-py-plugins==0.4.1
mdurl==0.1.2
mistune==3.0.2
more-itertools==10.4.0
msgpack==1.0.8
multidict==6.0.5
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
nh3==0.2.18
nltk==3.9.1
notebook==7.2.2
notebook_shim==0.2.4
numpy==1.26.4
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pandocfilters==1.5.1
panel==1.4.4
param==2.1.1
paramiko==3.4.1
parso==0.8.4
pillow==10.4.0
Pint==0.24.3
pkginfo==1.10.0
platformdirs==4.2.2
plumbum==1.8.3
pooch==1.8.2
prometheus_client==0.20.0
prompt_toolkit==3.0.47
proto-plus==1.24.0
protobuf==3.20.3
psutil==6.0.0
pure_eval==0.2.3
pyaedt==0.9.11
pyansys==2024.2.4
pyansys-tools-variableinterop==0.1.1
pyansys-tools-versioning==0.6.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pydantic==2.8.2
pydantic_core==2.20.1
pyedb==0.23.0
Pygments==2.18.0
pygranta==2024.2.0
pyiges==0.3.1
PyJWT==2.9.0
PyNaCl==1.5.0
pyparsing==3.1.4
pypiwin32==223
pypng==0.20220715.0
pyproject_hooks==1.1.0
Pyro5==5.15
pyspnego==0.11.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-json-logger==2.0.7
pytomlpp==1.0.13
pytwin==0.7.0
pytz==2024.1
pyvista==0.43.4
pyviz_comms==3.0.3
pywin32==306
pywin32-ctypes==0.2.3
pywinpty==2.0.13
PyYAML==6.0.2
pyzmq==26.2.0
readme_renderer==44.0
referencing==0.35.1
regex==2024.7.24
requests==2.32.3
requests-negotiate-sspi==0.5.2
requests-toolbelt==1.0.0
requests_ntlm==1.3.0
rfc3339-validator==0.1.4
rfc3986==2.0.0
rfc3986-validator==0.1.1
rich==13.8.0
rpds-py==0.20.0
rpyc==6.0.0
rsa==4.9
Rtree==1.3.0
scikit-rf==1.3.0
scipy==1.14.1
scooby==0.10.0
semver==3.0.2
Send2Trash==1.8.3
serpent==1.41
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
sqlparse==0.5.1
sseclient-py==1.8.0
sspilib==0.1.0
stack-data==0.6.3
tabulate==0.9.0
terminado==0.18.1
tinycss2==1.3.0
toml==0.10.2
tomli==2.0.1
tornado==6.4.1
tqdm==4.66.5
traitlets==5.14.3
trame==3.6.3
trame-client==3.2.5
trame-server==3.1.2
trame-vtk==2.8.10
trame-vuetify==2.7.1
twine==5.1.1
types-python-dateutil==2.9.0.20240821
typing_extensions==4.12.2
tzdata==2024.1
uc-micro-py==1.0.3
uri-template==1.3.0
uritemplate==4.1.1
urllib3==1.26.20
vtk==9.3.1
wakepy==0.9.1
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
websockets==12.0
widgetsnbextension==4.0.13
WMI==1.5.1
wrapt==1.16.0
wslink==2.1.2
xmlschema==2.5.1
xyzservices==2024.9.0
yarl==1.9.7
zipp==3.20.1
```

**Comment by dkowollik** [comment]
Hi @agrishin,
I think that I had the same issue with Ansys 2024R2 yesterday. In my case I identified it to be a file format issue. There is something wrong with the importers of SpaceClaim that are used within pyansys at the moment. They introduced a new SpaceClaim format *.scdocx, which is based on Parasolid. I think *.scdoc is based on ACIS and will be dropped sooner or later. Unfortunately, the current PyPrime versions do not support the old file format *.scdoc at the moment. I will create a bug report for this later today. Other formats like dsco, fmd or step should work for now. You could also use PyGeometry to open the *.scdoc format and save it as *.scdocx. 
I hope this helps for now. Maybe someone from the developer team as a better advice or explanation for this.

**Comment by agrishin** [comment]
Thanks! I'll pass that along to our customer...!

**Comment by costasva** [comment]
This seems to be a more general issue in my case. I am getting the same error if I try to read a STEP or Parasolid file.

**Comment by waltersma** [comment]
Hi @agrishin ,

I hope you do not mind but I edited your message to remove your customers name details as I think this was probably unintended to include this information.

Both SCDOC and SCDOCX are supported formats.  

PyPrimeMesh has a one-to-one compatibility between client server.  Please check you are using the correct versions as the details you provided appear to show use of 0.6.2 client with 2024R1 server.

Can you confirm that the installation you have for Ansys has the CAD configuration done and that you have SpaceClaim installed.  Do the files read into SpaceClaim standalone correctly?

We have seen reports of an issue with the Ansys Python Manager causing issues with CAD import.  Please can you setup a virtual environment separately and confirm if CAD import is working outside of using the Ansys Python Manager?

Thanks

**Comment by costasva** [comment]
Issue resolved, steps that made it work:
1 - Run C:\Program Files\ANSYS Inc\v242\ProductConfig.exe to configure CAD interfaces
2 - Run SpaceClaim manually and load an SCDOC file to make sure that any firewall exceptions are put in place (this happens the first time ANSYS products are run after installation)
3 - Create a venv and install PyPrimeMesh 0.6.2 (assuming we are using with ANSYS 2024R2). DO NOT use the ANSYS provided python package manager. 

*QUESTION* - How does PyPrimeMesh determine which ANSYS installation to use if there are multiple ones available? Is there a Prime equivalent to the ANSYS_DPF_PATH environment variable that points DPF to a particular installation?

**Comment by dkowollik** [comment]
Hi @costasva, 
good question. I debugged into the launch_prime method of 0.6.2. That is what I found out: 
If you run `prime.launch_prime()` it will always search for the available ansys licenses and take the highest version, see screenshot:
![grafik](https://github.com/user-attachments/assets/451ddfb0-cd87-4f89-b8d9-4725d6210465)
At the moment prime is using the AWP_ROOT242 environment variable, because 242 is the only version that is supported in 0.6.2 
![grafik](https://github.com/user-attachments/assets/baa9ea82-a476-4107-ba3d-bc3cd23cee15)

For a specific version you can use the prime_root parameter.
```python
from ansys.meshing import prime
prime_client = prime.launch_prime(prime_root=r'C:\Program Files\ANSYS Inc\v242\meshing\Prime')
```

I think adding an environment variable like in DPF would be a good enhancement. In general it would be great, if all pyansys packages would show a similar behaviour and provide similar options to launch the server.

**Comment by waltersma** [comment]
Closing as resolved.
